# Generated by Django 4.2.4 on 2023-08-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero_casa', models.CharField(max_length=10, verbose_name='Nº')),
                ('complemento', models.CharField(max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name_plural': 'Enderecos',
                'db_table': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('numero_pedido', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nº Pedido')),
                ('hora_limite', models.DateTimeField(blank=True, null=True, verbose_name='Horário Limite')),
                ('info_adicional', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FreteApp.endereco')),
            ],
            options={
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
    ]
