# Generated by Django 4.2.4 on 2023-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='valor_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
