# Generated by Django 4.2.4 on 2023-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0002_entrega_valor_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='criado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega Criada'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hora_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregar até'),
        ),
    ]
