# Generated by Django 4.2.4 on 2023-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0004_alter_entrega_hora_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
